pipeline {
    agent any

    stages {
        stage('Build and Deploy') {
            steps {
                sh '''
                    sudo docker build -t hrthummala/devxpace:karthik-${version} DockerHub/
                    sudo docker push hrthummala/devxpace:karthik-${version}
                   '''          
            }
         }
    }
}
