pipeline {
    agent any

    stages {
        stage('Build and Deploy') {
            steps {
                sh '''
                    docker build -t hrthummala/devxpace:nicejob-${version} DockerHub
                    docker push hrthummala/devxpace:nicejob-${version}
                   '''          
            }
         }
    }
}
